### ISSUE TITLE
First move only

### ISSUE THREAD

**Issue by jasperan** [JacobPox/LichessBot#1]
It only performs the first move.

**Comment by jklott** [comment]
> It only performs the first move.

I'm not able to repeat this problem. Which version are you trying to use?

**Comment by jasperan** [comment]
I was trying to use this section

https://github.com/JacobPox/LichessBot/tree/437eb9dea6a0e166210d4430ae58a0943bca7a2c

**Comment by jasperan** [comment]
Problem's fixed now. You may close the issue. One more thing, it seems like after one game, my lichess website is stuck on reconnecting. I've used the legit javascript, however I think I am getting banned anyways. Any tip?

**Comment by jklott** [comment]
> Problem's fixed now. You may close the issue. One more thing, it seems like after one game, my lichess website is stuck on reconnecting. I've used the legit javascript, however I think I am getting banned anyways. Any tip?

The way to know if lichess has banned you is to see if there are any online matches. If it shows none, you've been banned. Using my script against real players is a bannable offense. If you use it against the bot, that should not ban your account.
